language: python

sudo: false

services:
  - cassandra
  - rabbitmq

matrix:
  include:
    - python: 2.7
      env: NUMPY=1.9 SCIPY=0.15
    - python: 3.4
      env: NUMPY=1.9 SCIPY=0.15

before_install:
# - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
 - travis_retry wget http://repo.continuum.io/miniconda/Miniconda-3.8.3-Linux-x86_64.sh -O miniconda.sh
 - chmod +x miniconda.sh
 - bash miniconda.sh -b -p $HOME/miniconda
 - export PATH=/home/travis/miniconda/bin:$PATH
 - conda update --yes conda

install:
 - conda install --yes numpy=$NUMPY scipy=$SCIPY matplotlib pip
 - conda install --yes -c dan_blanchard python-coveralls
 - pip install setuptools
# - pip install https://github.com/johnbywater/eventsourcing/archive/develop.zip
 - pip install -r requirements.txt

script:
 - coverage run --source quantdsl -m unittest discover quantdsl

after_success:
  - coveralls --config_file .coveragerc
